### ISSUE TITLE
Error 400 Bad Request on /burp/proxy/history and /burp/target/sitemap

### ISSUE THREAD

**Issue by y4ppieflu** [vmware/burp-rest-api#91]
When Burp's history is populated with some requests to application, the burp-rest-api fails to return data on /burp/proxy/history and /burp/target/sitemap and instead returns the following error:
```
Whitelabel Error Page
This application has no explicit mapping for /error, so you are seeing this as a fallback.

Thu Aug 08 07:30:51 PDT 2019
There was an unexpected error (type=Bad Request, status=400).
URLDecoder: Illegal hex characters in escape (%) pattern - For input string: "8""
```
No additional error information is returned to console output and all other endpoints seem to work fine. 

Burp Pro v2.1.03
burp-rest-api v2.0.1

**Comment by ikkisoft** [comment]
Should be fixed. Cheers!

**Comment by hardikrana437** [comment]
Still facing the issue @thypon @ikkisoft 
{
  "timestamp": "2020-06-25T20:04:39.589+0000",
  "status": 400,
  "error": "Bad Request",
  "message": "URLDecoder: Illegal hex characters in escape (%) pattern - Error at index 1 in: \"1$\"",
  "path": "/burp/proxy/history"
}

**Comment by vinilnarayan** [comment]
Hi,
I'm getting below error while accessing  /burp/proxy/history

```
Whitelabel Error Page
This application has no explicit mapping for /error, so you are seeing this as a fallback.

Wed May 11 23:35:11 IST 2022
There was an unexpected error (type=Internal Server Error, status=500).
org.springframework.web.util.NestedServletException: Request processing failed; nested exception is org.springframework.http.converter.HttpMessageConversionException: Could not create JAXBContext for class [class com.vmware.burp.extension.domain.HttpMessageList]: Implementation of JAXB-API has not been found on module path or classpath.; nested exception is javax.xml.bind.JAXBException: Implementation of JAXB-API has not been found on module path or classpath. - with linked exception: [java.lang.ClassNotFoundException: com.sun.xml.bind.v2.ContextFactory]
```
